from __future__ import annotations

from cryoet_organizer.job_catalog import CatalogField, CatalogJob


TOMOGRAM_JOBS: tuple[CatalogJob, ...] = (
    CatalogJob(
        namespace="Tomograms",
        group="CryoLithe: Denoising",
        job_key="cryolithe_denoising",
        title="CryoLithe: Denoising",
        fields=(
            CatalogField("save_dir", "Save directory", widget="path", required=True),
            CatalogField("model_dir", "Model directory", widget="path", advanced=True),
            CatalogField("device", "Device", default_value="0", advanced=True),
            CatalogField("n3", "n3", default_value="256", advanced=True),
            CatalogField("batch_size", "Batch size", default_value="50000", advanced=True),
        ),
    ),
    CatalogJob(
        namespace="Tomograms",
        group="PyTom: Template matching",
        job_key="pytom_template_matching",
        title="PyTom: Template matching",
        fields=(
            CatalogField("template", "Template", widget="path", required=True),
            CatalogField("destination", "Destination", widget="path", required=True),
            CatalogField("mask", "Mask", widget="path", required=True),
            CatalogField("gpu_ids", "GPU IDs", default_value="0", required=True),
            CatalogField("manual_tomogram_input", "Input TS directory manually", widget="bool", advanced=True),
            CatalogField("manual_tomogram_dir", "Manual tomogram directory", widget="path", advanced=True),
            CatalogField("non_spherical_mask", "Non-spherical mask", widget="bool", advanced=True),
            CatalogField("particle_diameter", "Particle diameter", advanced=True),
            CatalogField("angular_search", "Angular search", advanced=True),
            CatalogField("z_axis_rotational_symmetry", "Z-axis rotational symmetry", default_value="1", advanced=True),
            CatalogField("volume_split", "Volume split", default_value="1 1 1", advanced=True),
            CatalogField("search_x", "Search X", advanced=True),
            CatalogField("search_y", "Search Y", advanced=True),
            CatalogField("search_z", "Search Z", advanced=True),
            CatalogField("tomogram_mask", "Tomogram mask directory", widget="path", advanced=True),
            CatalogField("per_tilt_weighting", "Per-tilt weighting", widget="bool", advanced=True),
            CatalogField("voxel_size_angstrom", "Voxel size angstrom", advanced=True),
            CatalogField("low_pass", "Low-pass", advanced=True),
            CatalogField("high_pass", "High-pass", advanced=True),
            CatalogField("dose_accumulation", "Dose accumulation", widget="path", advanced=True),
            CatalogField("defocus", "Defocus", widget="path", advanced=True),
            CatalogField("amplitude_contrast", "Amplitude contrast", advanced=True),
            CatalogField("spherical_aberration", "Spherical aberration", advanced=True),
            CatalogField("voltage", "Voltage", advanced=True),
            CatalogField("phase_shift", "Phase shift", default_value="0.0", advanced=True),
            CatalogField(
                "tomogram_ctf_model",
                "Tomogram CTF model",
                widget="choice",
                options=("phase-flip",),
                advanced=True,
            ),
            CatalogField(
                "defocus_handedness",
                "Defocus handedness",
                widget="choice",
                default_value="0",
                options=("-1", "0", "1"),
                advanced=True,
            ),
            CatalogField("spectral_whitening", "Spectral whitening", widget="bool", advanced=True),
            CatalogField("random_phase_correction", "Random phase correction", widget="bool", advanced=True),
            CatalogField("half_precision", "Half precision", widget="bool", advanced=True),
            CatalogField("rng_seed", "RNG seed", advanced=True),
            CatalogField("relion5_tomograms_star", "RELION5 tomograms.star", widget="path", advanced=True),
            CatalogField("warp_xml_file", "Use Warp XML file", widget="bool", advanced=False),
            CatalogField(
                "log",
                "Log level",
                widget="choice",
                default_value="INFO",
                options=("INFO", "DEBUG", "info", "debug"),
                advanced=True,
            ),
        ),
    ),
    CatalogJob(
        namespace="Tomograms",
        group="PyTom: Extract coordinates",
        job_key="pytom_extract_coordinates",
        title="PyTom: Extract coordinates",
        fields=(
            CatalogField("tm_output_folder", "PyTom TM output folder", widget="path", required=True),
            CatalogField("number_of_particles", "Number of particles", required=True),
            CatalogField("tomogram_mask", "Tomogram mask directory", widget="path", advanced=True),
            CatalogField("ignore_tomogram_mask", "Ignore tomogram mask", widget="bool", advanced=True),
            CatalogField("number_of_false_positives", "Number of false positives", default_value="1.0", advanced=True),
            CatalogField("particle_diameter", "Particle diameter", advanced=True),
            CatalogField("cut_off", "Cut-off", advanced=True),
            CatalogField("tophat_filter", "Tophat filter", widget="bool", advanced=True),
            CatalogField("tophat_connectivity", "Tophat connectivity", default_value="1", advanced=True),
            CatalogField("relion5_compat", "RELION5 compat", widget="bool", advanced=True),
            CatalogField(
                "log",
                "Log level",
                widget="choice",
                default_value="INFO",
                options=("INFO", "DEBUG", "info", "debug"),
                advanced=True,
            ),
            CatalogField("tophat_bins", "Tophat bins", default_value="50", advanced=True),
            CatalogField("plot_bins", "Plot bins", default_value="20", advanced=True),
        ),
    ),
    CatalogJob(
        namespace="Tomograms",
        group="Slabify: Mask creation",
        job_key="slabify_mask_creation",
        title="Slabify: Mask creation",
        fields=(
            CatalogField("output_directory", "Output directory", widget="path", required=True),
            CatalogField("manual_input", "Input directory manually", widget="bool", advanced=True),
            CatalogField("input_directory", "Input directory", widget="path", advanced=True),
            CatalogField("output_masked_directory", "Output masked directory", widget="path", advanced=True),
            CatalogField("border", "Border", default_value="0", advanced=True),
            CatalogField("offset", "Offset", default_value="0", advanced=True),
            CatalogField("angpix", "Angpix", advanced=True),
            CatalogField("measure", "Measure", widget="bool", advanced=True),
            CatalogField("points", "Points model", widget="path", advanced=True),
            CatalogField("n_samples", "Number of samples", default_value="50000", advanced=True),
            CatalogField("boxsize", "Box size", default_value="32", advanced=True),
            CatalogField("z_min", "Z min", default_value="1", advanced=True),
            CatalogField("z_max", "Z max", advanced=True),
            CatalogField("iterations", "Iterations", default_value="3", advanced=True),
            CatalogField("simple", "Simple fit", widget="bool", advanced=True),
            CatalogField("thickness", "Thickness", advanced=True),
            CatalogField("percentile", "Percentile", default_value="95", advanced=True),
            CatalogField("seed", "Seed", default_value="4056", advanced=True),
        ),
    ),
    CatalogJob(
        namespace="Tomograms",
        group="MemBrain-seg: Segmentation",
        job_key="membrain_segmentation",
        title="MemBrain-seg: Segmentation",
        fields=(
            CatalogField("ckpt_path", "Checkpoint path", widget="path", required=True),
            CatalogField("out_folder", "Output folder", widget="path", default_value="predictions", required=True),
            CatalogField("manual_input", "Input TS directory manually", widget="bool", advanced=True),
            CatalogField("input_directory", "Input directory", widget="path", advanced=True),
            CatalogField("rescale_patches", "Rescale patches", widget="bool", advanced=True),
            CatalogField("in_pixel_size", "Input pixel size", advanced=True),
            CatalogField("out_pixel_size", "Output pixel size", default_value="10.0", advanced=True),
            CatalogField("store_probabilities", "Store probabilities", widget="bool", advanced=True),
            CatalogField("store_connected_components", "Store connected components", widget="bool", advanced=True),
            CatalogField("connected_component_threshold", "Connected component threshold", advanced=True),
            CatalogField("test_time_augmentation", "Test-time augmentation", widget="bool", default_value="true", advanced=True),
            CatalogField("segmentation_threshold", "Segmentation threshold", default_value="0.0", advanced=True),
            CatalogField("sliding_window_size", "Sliding window size", default_value="160", advanced=True),
        ),
    ),
)


def tomogram_jobs_by_title() -> dict[str, CatalogJob]:
    return {job.title: job for job in TOMOGRAM_JOBS}


def tomogram_job_titles() -> tuple[str, ...]:
    return tuple(job.title for job in TOMOGRAM_JOBS)
